# Generated by Django 3.1.2 on 2020-10-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=8, null=True),
        ),
    ]
